include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    sdk_version_async_exported_from_core: ignore
    unnecessary_null_comparison: ignore

linter:
  rules:
    prefer_relative_imports: false
    prefer_single_quotes: true
    avoid_void_async: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_new: true
    unnecessary_parenthesis: true
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
    prefer_if_elements_to_conditional_expressions: true
    avoid_function_literals_in_foreach_calls: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    directives_ordering: true
    cast_nullable_to_non_nullable: true
    flutter_style_todos: true
    annotate_overrides: true
    unnecessary_await_in_return: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    no_logic_in_create_state: true
    avoid_unnecessary_containers: true
    always_require_non_null_named_parameters: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cancel_subscriptions: true
    control_flow_in_finally: true
    empty_constructor_bodies: true
    empty_statements: true
    exhaustive_cases: true
    hash_and_equals: true
    implementation_imports: true
    iterable_contains_unrelated_type: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    null_check_on_nullable_type_parameter: true
    null_closures: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_contains: true
    prefer_final_in_for_each: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    constant_identifier_names: false
    non_constant_identifier_names: false
    no_leading_underscores_for_local_identifiers: false
